import {
  Outlet,
  Product,
  OutletProduct,
  Offer,
  Vendor,
  Licence,
  CustomerMembership,
  VendorSubscription,
  SupportTicket,
  AuditLog,
  AnalyticsAggregate,
} from '../types';

export interface DutyFreeProduct extends Product {
  dutyFreePrice?: number;
  discountPercentage?: number;
  isDutyFreeExclusive?: boolean;
  rating?: number;
  reviewCount?: number;
  tastingNotes?: string[];
}

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'v1',
    legalName: 'Gurgaon Prime Spirits Pvt Ltd',
    tradeName: 'L1 Discovery Hub — Cyber City',
    ownerUid: 'user_vendor_1',
    gstin: '06AAACG1234F1Z5',
    status: 'ACTIVE',
    jurisdictionId: 'HR',
    complianceStatus: 'APPROVED',
    createdAt: '2025-06-15T10:00:00Z',
    updatedAt: '2025-06-15T10:00:00Z',
  },
  {
    id: 'v2',
    legalName: 'Heritage Liquor Traders LLC',
    tradeName: 'The Vault Fine Wines & Spirits — Sector 29',
    ownerUid: 'user_vendor_2',
    gstin: '06BBBCH5678G2Z9',
    status: 'ACTIVE',
    jurisdictionId: 'HR',
    complianceStatus: 'APPROVED',
    createdAt: '2025-07-01T12:00:00Z',
    updatedAt: '2025-07-01T12:00:00Z',
  },
  {
    id: 'v3',
    legalName: 'Royal Cellars Faridabad Corp',
    tradeName: 'Grand Cellar Outlets — Sector 15 Faridabad',
    ownerUid: 'user_vendor_3',
    gstin: '06CCDCK9101H3Z2',
    status: 'ACTIVE',
    jurisdictionId: 'HR',
    complianceStatus: 'APPROVED',
    createdAt: '2025-08-10T09:00:00Z',
    updatedAt: '2025-08-10T09:00:00Z',
  },
];

export const INITIAL_LICENCES: Licence[] = [
  {
    id: 'lic_1',
    outletId: 'out_1',
    vendorId: 'v1',
    type: 'L-2',
    number: 'HR-GUR-L2-2025-0042',
    issueDate: '2025-06-12',
    expiryDate: '2027-03-31',
    authority: 'Excise & Taxation Department, Govt of Haryana',
    documentPath: 'licences/v1_l2_cert.pdf',
    documentName: 'Haryana_L2_Licence_CyberHub_2025_27.pdf',
    verificationStatus: 'APPROVED',
    reviewerNotes: 'Verified against official licensee database search.',
    reviewedBy: 'compliance_officer_1',
    reviewedAt: '2025-06-14T11:00:00Z',
  },
  {
    id: 'lic_2',
    outletId: 'out_2',
    vendorId: 'v2',
    type: 'L-14A',
    number: 'HR-GUR-L14A-2025-0108',
    issueDate: '2025-06-12',
    expiryDate: '2027-03-31',
    authority: 'Excise & Taxation Department, Govt of Haryana',
    documentPath: 'licences/v2_l14a_cert.pdf',
    documentName: 'Haryana_L14A_Sector29_Certificate.pdf',
    verificationStatus: 'APPROVED',
    reviewerNotes: 'All premises documents verified.',
    reviewedBy: 'compliance_officer_1',
    reviewedAt: '2025-07-02T15:20:00Z',
  },
  {
    id: 'lic_3',
    outletId: 'out_3',
    vendorId: 'v3',
    type: 'L-2',
    number: 'HR-FAR-L2-2025-0077',
    issueDate: '2025-06-12',
    expiryDate: '2027-03-31',
    authority: 'Excise & Taxation Department, Govt of Haryana',
    documentPath: 'licences/v3_faridabad_cert.pdf',
    documentName: 'Haryana_L2_Faridabad_Sector15.pdf',
    verificationStatus: 'APPROVED',
    reviewerNotes: 'Approved for Faridabad pilot launch.',
    reviewedBy: 'compliance_officer_1',
    reviewedAt: '2025-08-11T10:15:00Z',
  },
];

export const INITIAL_OUTLETS: Outlet[] = [
  {
    id: 'out_1',
    vendorId: 'v1',
    name: 'L1 Discovery Outlet — Cyber Hub',
    address: 'Building 10-A, DLF Cyber City, Phase 2, Gurugram',
    geoPoint: { lat: 28.4952, lng: 77.0886 },
    district: 'Gurugram',
    zone: 'Cyber City Hub',
    licenceIds: ['lic_1'],
    status: 'ACTIVE',
    isVerified: true,
    hours: { open: '10:00', close: '23:30', daysOpen: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    phone: '+91 98100 12345',
    images: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80'],
    rating: 4.9,
    createdAt: '2025-06-15T10:00:00Z',
  },
  {
    id: 'out_2',
    vendorId: 'v2',
    name: 'The Vault Fine Spirits — Sector 29',
    address: 'SCO 45-46, Sector 29 Market, Gurugram',
    geoPoint: { lat: 28.4682, lng: 77.0632 },
    district: 'Gurugram',
    zone: 'Sector 29 Hub',
    licenceIds: ['lic_2'],
    status: 'ACTIVE',
    isVerified: true,
    hours: { open: '10:00', close: '23:00', daysOpen: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    phone: '+91 98111 67890',
    images: ['https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=80'],
    rating: 4.8,
    createdAt: '2025-07-01T12:00:00Z',
  },
  {
    id: 'out_3',
    vendorId: 'v3',
    name: 'Grand Cellar Outlets — Sector 15 Faridabad',
    address: 'Main Market Road, Sector 15, Faridabad',
    geoPoint: { lat: 28.3962, lng: 77.3178 },
    district: 'Faridabad',
    zone: 'Sector 15 Zone',
    licenceIds: ['lic_3'],
    status: 'ACTIVE',
    isVerified: true,
    hours: { open: '10:00', close: '22:30', daysOpen: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    phone: '+91 98188 43210',
    images: ['https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80'],
    rating: 4.7,
    createdAt: '2025-08-10T09:00:00Z',
  },
];

export const INITIAL_PRODUCTS: DutyFreeProduct[] = [
  {
    id: 'p_gold_champagne',
    brandId: 'b_armand',
    brandName: 'Armand de Brignac',
    productName: 'Ace of Spades Gold Brut Champagne',
    category: 'Wine',
    packSizes: ['750ml'],
    abv: 12.5,
    countryOfOrigin: 'France',
    description: 'The world-famous prestige cuvée presented in a metallic gold bottle with hand-applied pewter Ace of Spades crests. Notes of peach, brioche, and golden honey finish.',
    imageUrl: 'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { '750ml': 38500 },
    dutyFreePrice: 31900,
    discountPercentage: 17,
    isDutyFreeExclusive: true,
    rating: 4.9,
    reviewCount: 142,
    tastingNotes: ['Brioche', 'Golden Apple', 'White Peach', 'Subtle Toast'],
    status: 'ACTIVE',
  },
  {
    id: 'p_dom_perignon',
    brandId: 'b_dom',
    brandName: 'Dom Pérignon',
    productName: 'Vintage Gold Reserve Champagne',
    category: 'Wine',
    packSizes: ['750ml'],
    abv: 12.5,
    countryOfOrigin: 'France',
    description: 'Vibrant, intense bouquet featuring candied citrus fruit, toasted almonds, and subtle golden minerality. Exceptional aging potential.',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { '750ml': 29500 },
    dutyFreePrice: 24200,
    discountPercentage: 18,
    isDutyFreeExclusive: true,
    rating: 4.9,
    reviewCount: 210,
    tastingNotes: ['Smoky Cocoa', 'Toasted Almond', 'Candied Citrus'],
    status: 'ACTIVE',
  },
  {
    id: 'p1',
    brandId: 'b_glenfiddich',
    brandName: 'Glenfiddich',
    productName: '12 Year Old Single Malt Scotch Whisky',
    category: 'Single Malt',
    packSizes: ['750ml', '1000ml'],
    abv: 40,
    countryOfOrigin: 'Scotland',
    description: 'Flowery, fresh pear and subtle oak aromas. Matured in Spanish Oloroso wood and American oak casks for a velvety finish.',
    imageUrl: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { '750ml': 3990, '1000ml': 4950 },
    dutyFreePrice: 3450,
    discountPercentage: 14,
    isDutyFreeExclusive: false,
    rating: 4.8,
    reviewCount: 380,
    tastingNotes: ['Fresh Pear', 'Subtle Oak', 'Butterscotch'],
    status: 'ACTIVE',
  },
  {
    id: 'p2',
    brandId: 'b_macallan',
    brandName: 'The Macallan',
    productName: 'Double Cask 12 Years Old Single Malt',
    category: 'Single Malt',
    packSizes: ['750ml'],
    abv: 40,
    countryOfOrigin: 'Scotland',
    description: 'Perfect harmony of 100% sherry seasoned American and European oak casks producing rich fudge and citrus notes.',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { '750ml': 6850 },
    dutyFreePrice: 5790,
    discountPercentage: 15,
    isDutyFreeExclusive: true,
    rating: 4.9,
    reviewCount: 415,
    tastingNotes: ['Butterscotch', 'Toffee Apple', 'Candied Orange'],
    status: 'ACTIVE',
  },
  {
    id: 'p_hibiki',
    brandId: 'b_hibiki',
    brandName: 'Suntory Hibiki',
    productName: 'Hibiki Japanese Harmony Whisky',
    category: 'Single Malt',
    packSizes: ['700ml' as any],
    abv: 43,
    countryOfOrigin: 'Japan',
    description: 'A meticulous blend of select fine whiskies from Yamazaki, Hakushu, and Chita distilleries. Delicate honey, orange peel, and Mizunara oak.',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { '700ml': 12500 },
    dutyFreePrice: 9900,
    discountPercentage: 20,
    isDutyFreeExclusive: true,
    rating: 4.95,
    reviewCount: 290,
    tastingNotes: ['Rose', 'Lychee', 'Rosemary', 'Sandalwood'],
    status: 'ACTIVE',
  },
  {
    id: 'p3',
    brandId: 'b_monkey47',
    brandName: 'Monkey 47',
    productName: 'Schwarzwald Dry Gin Premium Edition',
    category: 'Gin',
    packSizes: ['500ml' as any],
    abv: 47,
    countryOfOrigin: 'Germany',
    description: 'Crafted with 47 handpicked botanicals including Black Forest cranberries and lingonberries. Unrivalled botanical aromatic density.',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { '500ml': 4200 },
    dutyFreePrice: 3500,
    discountPercentage: 16,
    isDutyFreeExclusive: false,
    rating: 4.8,
    reviewCount: 175,
    tastingNotes: ['Juniper', 'Cranberry', 'Wood Spruce', 'Citrus Peel'],
    status: 'ACTIVE',
  },
  {
    id: 'p4',
    brandId: 'b_greygoose',
    brandName: 'Grey Goose',
    productName: 'Grey Goose VX Premium Wheat Vodka',
    category: 'Vodka',
    packSizes: ['750ml', '1000ml'],
    abv: 40,
    countryOfOrigin: 'France',
    description: 'Distilled in Picardie from French winter wheat and blended with pure Gensac spring water. Finished with drops of precious Cognac.',
    imageUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { '750ml': 3450, '1000ml': 4400 },
    dutyFreePrice: 2890,
    discountPercentage: 16,
    isDutyFreeExclusive: false,
    rating: 4.7,
    reviewCount: 310,
    tastingNotes: ['Plum', 'Apricot', 'Wild Honey', 'White Peach'],
    status: 'ACTIVE',
  },
  {
    id: 'p5',
    brandId: 'b_corona',
    brandName: 'Corona',
    productName: 'Corona Extra Premium Golden Lager Pack',
    category: 'Beer',
    packSizes: [' Pint 330ml'],
    abv: 4.5,
    countryOfOrigin: 'Mexico',
    description: 'Crisp golden lager brewed with malted barley and hops for a refreshing smooth finish.',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { ' Pint 330ml': 210 },
    dutyFreePrice: 175,
    discountPercentage: 16,
    isDutyFreeExclusive: false,
    rating: 4.6,
    reviewCount: 520,
    tastingNotes: ['Malt Crisp', 'Honey Notes', 'Smooth Lime'],
    status: 'ACTIVE',
  },
  {
    id: 'p6',
    brandId: 'b_jacobscreek',
    brandName: "Jacob's Creek",
    productName: "Jacob's Creek Double Barrel Shiraz",
    category: 'Wine',
    packSizes: ['750ml'],
    abv: 14.2,
    countryOfOrigin: 'Australia',
    description: 'Finished in vintage Scotch whisky barrels for extraordinary dark plum fruit intensity and silky cocoa tannins.',
    imageUrl: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80',
    mrpGuide: { '750ml': 2100 },
    dutyFreePrice: 1720,
    discountPercentage: 18,
    isDutyFreeExclusive: false,
    rating: 4.7,
    reviewCount: 230,
    tastingNotes: ['Blackberry', 'Dark Chocolate', 'Whisky Spice'],
    status: 'ACTIVE',
  },
];

export const INITIAL_OUTLET_PRODUCTS: OutletProduct[] = [
  {
    id: 'op_gold_1',
    outletId: 'out_1',
    productId: 'p_gold_champagne',
    packSize: '750ml',
    availabilityStatus: 'IN_STOCK',
    priceIfApproved: 38500,
    source: 'VERIFIED_SIGNAL',
    observedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'op_gold_2',
    outletId: 'out_2',
    productId: 'p_gold_champagne',
    packSize: '750ml',
    availabilityStatus: 'LOW_STOCK',
    priceIfApproved: 38500,
    source: 'VENDOR_PORTAL',
    observedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'op_dom_1',
    outletId: 'out_1',
    productId: 'p_dom_perignon',
    packSize: '750ml',
    availabilityStatus: 'IN_STOCK',
    priceIfApproved: 29500,
    source: 'VENDOR_PORTAL',
    observedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'op_hibiki_1',
    outletId: 'out_1',
    productId: 'p_hibiki',
    packSize: '700ml' as any,
    availabilityStatus: 'IN_STOCK',
    priceIfApproved: 12500,
    source: 'VERIFIED_SIGNAL',
    observedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'op1',
    outletId: 'out_1',
    productId: 'p1',
    packSize: '750ml',
    availabilityStatus: 'IN_STOCK',
    priceIfApproved: 3990,
    source: 'VENDOR_PORTAL',
    observedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'op2',
    outletId: 'out_1',
    productId: 'p2',
    packSize: '750ml',
    availabilityStatus: 'IN_STOCK',
    priceIfApproved: 6850,
    source: 'VERIFIED_SIGNAL',
    observedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'op3',
    outletId: 'out_2',
    productId: 'p3',
    packSize: '500ml' as any,
    availabilityStatus: 'IN_STOCK',
    priceIfApproved: 4200,
    source: 'VENDOR_PORTAL',
    observedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'op4',
    outletId: 'out_3',
    productId: 'p5',
    packSize: ' Pint 330ml',
    availabilityStatus: 'IN_STOCK',
    priceIfApproved: 210,
    source: 'VENDOR_PORTAL',
    observedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'off_gold',
    outletId: 'out_1',
    vendorId: 'v1',
    title: 'Duty Free Special: Free Twin 24K Gold Crystal Flutes',
    description: 'Receive twin 24k gold-rimmed Champagne flutes with verified discovery of Armand de Brignac Gold.',
    validFrom: '2026-08-01',
    validTo: '2026-10-31',
    status: 'LIVE',
    complianceStatus: 'APPROVED',
    terms: [
      'Permitted platform discovery gift accessory only.',
      'No direct discount on liquor MRP per Haryana Excise Rules.',
    ],
    productCategory: 'Wine',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'off_1',
    outletId: 'out_2',
    vendorId: 'v2',
    title: 'VIP Reserve Lounge Access for Platform Pro Members',
    description: 'Exclusive access to the Sector 29 Tasting Room during weekend discovery sessions.',
    validFrom: '2026-08-15',
    validTo: '2026-10-15',
    status: 'LIVE',
    complianceStatus: 'APPROVED',
    terms: ['Valid for Platform Pro Members only.'],
    createdAt: '2026-08-14T16:00:00Z',
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
export const INITIAL_ANALYTICS: AnalyticsAggregate = {
  date: '2026-09-01',
  district: 'Gurugram',
  totalSearches: 14250,
  outletViews: 8910,
  directionClicks: 3420,
  activeUsers: 6840,
  activeVendors: 42,
  mrrInr: 348000,
};
