import {
  PartnerStore,
  Product,
  EarlyAccessSale,
  Vendor,
  Licence,
  Offer,
  MembershipPlan,
  DutyFreeProduct,
} from '../types';

export type { DutyFreeProduct };

export const INITIAL_PRODUCTS: Product[] = [
  // --- CHAMPAGNES & FINE WINES ---
  {
    id: 'p_gold_champagne',
    brandId: 'b_armand',
    brandName: 'Armand de Brignac',
    productName: 'Ace of Spades Gold Brut Champagne 750ml',
    category: 'Wine',
    originType: 'IMPORTED',
    originCountry: 'France',
    countryOfOrigin: 'France',
    packSizes: ['750ml'],
    abv: 12.5,
    description: 'Prestige cuvée crafted from Grand Cru Chardonnay and Pinot Noir. Complex bouquet of peach, honeyed brioche, and golden citrus.',
    imageUrl: 'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?auto=format&fit=crop&w=800&q=80',
    regularPrice: 38500,
    memberPrice: 31900,
    dutyFreePrice: 31900,
    discountPercentage: 17,
    isEarlyAccess: true,
    isLimitedEdition: true,
    rating: 4.9,
    reviewCount: 142,
    tastingNotes: ['Brioche', 'Golden Apple', 'White Peach', 'Subtle Toast'],
    mrpGuide: { '750ml': 38500 },
    status: 'ACTIVE',
  },
  {
    id: 'p_dom_perignon',
    brandId: 'b_dom',
    brandName: 'Dom Pérignon',
    productName: 'Dom Pérignon Vintage Gold Reserve Champagne',
    category: 'Wine',
    originType: 'IMPORTED',
    originCountry: 'France',
    countryOfOrigin: 'France',
    packSizes: ['750ml'],
    abv: 12.5,
    description: 'Vibrant, intense bouquet featuring candied citrus fruit, toasted almonds, and subtle golden minerality.',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    regularPrice: 29500,
    memberPrice: 24200,
    dutyFreePrice: 24200,
    discountPercentage: 18,
    isEarlyAccess: false,
    isLimitedEdition: true,
    rating: 4.9,
    reviewCount: 210,
    tastingNotes: ['Smoky Cocoa', 'Toasted Almond', 'Candied Citrus'],
    mrpGuide: { '750ml': 29500 },
    status: 'ACTIVE',
  },

  // --- SINGLE MALTS & RARE WHISKIES ---
  {
    id: 'p2',
    brandId: 'b_macallan',
    brandName: 'The Macallan',
    productName: 'The Macallan Double Cask 12 Years Single Malt',
    category: 'Single Malt',
    originType: 'IMPORTED',
    originCountry: 'Scotland',
    countryOfOrigin: 'Scotland',
    packSizes: ['750ml'],
    abv: 40,
    description: 'Perfect harmony of 100% sherry seasoned American and European oak casks producing rich fudge and citrus notes.',
    imageUrl: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=80',
    regularPrice: 6850,
    memberPrice: 5790,
    dutyFreePrice: 5790,
    discountPercentage: 15,
    isEarlyAccess: true,
    rating: 4.9,
    reviewCount: 415,
    tastingNotes: ['Butterscotch', 'Toffee Apple', 'Candied Orange'],
    mrpGuide: { '750ml': 6850 },
    status: 'ACTIVE',
  },
  {
    id: 'p1',
    brandId: 'b_glenfiddich',
    brandName: 'Glenfiddich',
    productName: 'Glenfiddich 12 Year Old Single Malt Scotch Whisky',
    category: 'Single Malt',
    originType: 'IMPORTED',
    originCountry: 'Scotland',
    countryOfOrigin: 'Scotland',
    packSizes: ['750ml', '375ml', '180ml'],
    abv: 40,
    description: 'Flowery, fresh pear and subtle oak aromas. Matured in Spanish Oloroso wood and American oak casks for a velvety finish.',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    regularPrice: 3990,
    memberPrice: 3450,
    dutyFreePrice: 3450,
    discountPercentage: 14,
    isEarlyAccess: false,
    rating: 4.8,
    reviewCount: 380,
    tastingNotes: ['Fresh Pear', 'Subtle Oak', 'Butterscotch'],
    mrpGuide: { '750ml': 3990 },
    status: 'ACTIVE',
  },
  {
    id: 'p_hibiki',
    brandId: 'b_hibiki',
    brandName: 'Suntory Hibiki',
    productName: 'Suntory Hibiki Japanese Harmony Whisky',
    category: 'Single Malt',
    originType: 'IMPORTED',
    originCountry: 'Japan',
    countryOfOrigin: 'Japan',
    packSizes: ['700ml' as any],
    abv: 43,
    description: 'A meticulous blend of select fine whiskies from Yamazaki, Hakushu, and Chita distilleries. Delicate honey, orange peel, and Mizunara oak.',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=800&q=80',
    regularPrice: 12500,
    memberPrice: 9900,
    dutyFreePrice: 9900,
    discountPercentage: 20,
    isEarlyAccess: true,
    isLimitedEdition: true,
    rating: 4.95,
    reviewCount: 290,
    tastingNotes: ['Rose', 'Lychee', 'Rosemary', 'Sandalwood'],
    mrpGuide: { '750ml': 12500 },
    status: 'ACTIVE',
  },

  // --- LOCAL & COUNTRY MADE FINE INDIAN RESERVES ---
  {
    id: 'p_indri',
    brandId: 'b_indri',
    brandName: 'Indri',
    productName: 'Indri Trini Three Wood Indian Single Malt',
    category: 'Single Malt',
    originType: 'LOCAL',
    originCountry: 'India',
    countryOfOrigin: 'India',
    packSizes: ['750ml'],
    abv: 46,
    description: 'Award-winning Indian Single Malt aged in Bourbon, French Wine, and Sherry casks. Caramel, black tea, and tropical wood spice.',
    imageUrl: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=80',
    regularPrice: 3100,
    memberPrice: 2650,
    discountPercentage: 15,
    isEarlyAccess: false,
    rating: 4.9,
    reviewCount: 520,
    tastingNotes: ['Black Tea', 'Caramel', 'Oak Spice', 'Dried Apricot'],
    mrpGuide: { '750ml': 3100 },
    status: 'ACTIVE',
  },
  {
    id: 'p_amrut',
    brandId: 'b_amrut',
    brandName: 'Amrut',
    productName: 'Amrut Fusion Single Malt Indian Whisky',
    category: 'Single Malt',
    originType: 'LOCAL',
    originCountry: 'India',
    countryOfOrigin: 'India',
    packSizes: ['750ml'],
    abv: 50,
    description: 'World-renowned Indian single malt created from peated Scottish barley and unpeated Indian barley. Rich oak, vanilla, and smoke.',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    regularPrice: 3400,
    memberPrice: 2890,
    discountPercentage: 15,
    rating: 4.85,
    reviewCount: 460,
    tastingNotes: ['Heavy Oak', 'Peat Smoke', 'Fudge', 'Coffee'],
    mrpGuide: { '750ml': 3400 },
    status: 'ACTIVE',
  },
  {
    id: 'p_greater_than',
    brandId: 'b_greater_than',
    brandName: 'Greater Than',
    productName: 'Greater Than London Dry Indian Craft Gin',
    category: 'Gin',
    originType: 'LOCAL',
    originCountry: 'India',
    countryOfOrigin: 'India',
    packSizes: ['750ml'],
    abv: 42.8,
    description: 'Crafted in Goa with juniper, coriander seeds, chamomile, ginger, and lemongrass. Clean, crisp, and refreshing.',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    regularPrice: 1450,
    memberPrice: 1200,
    discountPercentage: 17,
    rating: 4.7,
    reviewCount: 310,
    tastingNotes: ['Fresh Lemongrass', 'Juniper', 'Ginger Snap'],
    mrpGuide: { '750ml': 1450 },
    status: 'ACTIVE',
  },

  // --- PREMIUM GIN & VODKA & TEQUILA ---
  {
    id: 'p3',
    brandId: 'b_monkey47',
    brandName: 'Monkey 47',
    productName: 'Monkey 47 Schwarzwald Dry Gin 500ml',
    category: 'Gin',
    originType: 'IMPORTED',
    originCountry: 'Germany',
    countryOfOrigin: 'Germany',
    packSizes: ['500ml' as any],
    abv: 47,
    description: 'Crafted with 47 handpicked botanicals including Black Forest cranberries and lingonberries. Unrivalled botanical aromatic density.',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    regularPrice: 4200,
    memberPrice: 3500,
    dutyFreePrice: 3500,
    discountPercentage: 16,
    rating: 4.8,
    reviewCount: 175,
    tastingNotes: ['Juniper', 'Cranberry', 'Wood Spruce', 'Citrus Peel'],
    mrpGuide: { '750ml': 4200 },
    status: 'ACTIVE',
  },
  {
    id: 'p4',
    brandId: 'b_greygoose',
    brandName: 'Grey Goose',
    productName: 'Grey Goose VX Premium Wheat Vodka 750ml',
    category: 'Vodka',
    originType: 'IMPORTED',
    originCountry: 'France',
    countryOfOrigin: 'France',
    packSizes: ['750ml', '1000ml'],
    abv: 40,
    description: 'Distilled in Picardie from French winter wheat and blended with pure Gensac spring water. Finished with drops of precious Cognac.',
    imageUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80',
    regularPrice: 3450,
    memberPrice: 2890,
    dutyFreePrice: 2890,
    discountPercentage: 16,
    rating: 4.7,
    reviewCount: 310,
    tastingNotes: ['Plum', 'Apricot', 'Wild Honey', 'White Peach'],
    mrpGuide: { '750ml': 3450 },
    status: 'ACTIVE',
  },
  {
    id: 'p_don_julio',
    brandId: 'b_don_julio',
    brandName: 'Don Julio',
    productName: 'Don Julio 1942 Añejo Tequila 750ml',
    category: 'Tequila',
    originType: 'IMPORTED',
    originCountry: 'Mexico',
    countryOfOrigin: 'Mexico',
    packSizes: ['750ml'],
    abv: 38,
    description: 'Celebrated in exclusive cocktail bars worldwide. Handcrafted in small batches and aged in oak barrels for warm oak, vanilla, and roasted agave.',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    regularPrice: 22000,
    memberPrice: 18500,
    discountPercentage: 16,
    isLimitedEdition: true,
    rating: 4.95,
    reviewCount: 185,
    tastingNotes: ['Warm Oak', 'Vanilla', 'Roasted Agave', 'Dark Cinnamon'],
    mrpGuide: { '750ml': 22000 },
    status: 'ACTIVE',
  },
  {
    id: 'p5',
    brandId: 'b_corona',
    brandName: 'Corona',
    productName: 'Corona Extra Premium Golden Lager Pack',
    category: 'Beer',
    originType: 'IMPORTED',
    originCountry: 'Mexico',
    countryOfOrigin: 'Mexico',
    packSizes: [' Pint 330ml'],
    abv: 4.5,
    description: 'Crisp golden lager brewed with malted barley and hops for a refreshing smooth finish.',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=800&q=80',
    regularPrice: 210,
    memberPrice: 175,
    discountPercentage: 16,
    rating: 4.6,
    reviewCount: 520,
    tastingNotes: ['Malt Crisp', 'Smooth Lime'],
    mrpGuide: { '750ml': 210 },
    status: 'ACTIVE',
  },
];

export const INITIAL_PARTNER_STORES: PartnerStore[] = [
  {
    id: 'out_1',
    vendorId: 'v1',
    name: 'L1 Discovery Hub — Cyber City',
    address: 'Building 10-A, DLF Cyber City, Phase 2, Gurugram, Haryana 122002',
    geoPoint: { lat: 28.4952, lng: 77.0886 },
    district: 'Gurugram',
    zone: 'Cyber City Zone',
    licenceIds: ['lic_1'],
    status: 'ACTIVE',
    isVerified: true,
    hours: { open: '10:00', close: '23:30', daysOpen: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    phone: '+91 98100 12345',
    images: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80'],
    rating: 4.9,
    reviewCount: 420,
    maxMemberDiscountPercent: 20,
    estimatedDriveTimeMins: 5,
    inventory: {
      p_gold_champagne: { stock: 8, storePrice: 38500, storeMemberPrice: 31900, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
      p_dom_perignon: { stock: 5, storePrice: 29500, storeMemberPrice: 24200, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString() },
      p1: { stock: 15, storePrice: 3990, storeMemberPrice: 3450, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
      p2: { stock: 12, storePrice: 6850, storeMemberPrice: 5790, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
      p_hibiki: { stock: 4, storePrice: 12500, storeMemberPrice: 9900, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
      p_indri: { stock: 20, storePrice: 3100, storeMemberPrice: 2650, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
    },
    createdAt: '2025-06-15T10:00:00Z',
  },
  {
    id: 'out_2',
    vendorId: 'v2',
    name: 'The Vault Fine Wines & Spirits — Sector 29',
    address: 'SCO 45-46, Sector 29 Market, Gurugram, Haryana 122001',
    geoPoint: { lat: 28.4682, lng: 77.0632 },
    district: 'Gurugram',
    zone: 'Sector 29 Hub',
    licenceIds: ['lic_2'],
    status: 'ACTIVE',
    isVerified: true,
    hours: { open: '10:00', close: '23:00', daysOpen: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    phone: '+91 98111 67890',
    images: ['https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=800&q=80'],
    rating: 4.8,
    reviewCount: 310,
    maxMemberDiscountPercent: 18,
    estimatedDriveTimeMins: 8,
    inventory: {
      p_gold_champagne: { stock: 3, storePrice: 38500, storeMemberPrice: 31900, availabilityStatus: 'LOW_STOCK', observedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString() },
      p3: { stock: 10, storePrice: 4200, storeMemberPrice: 3500, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
      p_amrut: { stock: 14, storePrice: 3400, storeMemberPrice: 2890, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString() },
    },
    createdAt: '2025-07-01T12:00:00Z',
  },
  {
    id: 'out_3',
    vendorId: 'v3',
    name: 'Grand Cellar Outlets — Sector 15 Faridabad',
    address: 'Main Market Road, Sector 15, Faridabad, Haryana 121007',
    geoPoint: { lat: 28.3962, lng: 77.3178 },
    district: 'Faridabad',
    zone: 'Sector 15 Zone',
    licenceIds: ['lic_3'],
    status: 'ACTIVE',
    isVerified: true,
    hours: { open: '10:00', close: '22:30', daysOpen: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    phone: '+91 98188 43210',
    images: ['https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80'],
    rating: 4.7,
    reviewCount: 250,
    maxMemberDiscountPercent: 15,
    estimatedDriveTimeMins: 15,
    inventory: {
      p5: { stock: 50, storePrice: 210, storeMemberPrice: 175, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
      p_greater_than: { stock: 18, storePrice: 1450, storeMemberPrice: 1200, availabilityStatus: 'IN_STOCK', observedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString() },
    },
    createdAt: '2025-08-10T09:00:00Z',
  },
];

export const INITIAL_EARLY_ACCESS_SALES: EarlyAccessSale[] = [
  {
    id: 'ea_1',
    title: 'Members Only Exclusive: Armand de Brignac Gold Flash Lock',
    productId: 'p_gold_champagne',
    productName: 'Armand de Brignac Ace of Spades Gold Brut Champagne 750ml',
    brandName: 'Armand de Brignac',
    imageUrl: 'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?auto=format&fit=crop&w=800&q=80',
    regularPrice: 38500,
    memberPrice: 31900,
    startTime: new Date().toISOString(),
    endTime: new Date(Date.now() + 2 * 60 * 60 * 1000 + 14 * 60 * 1000 + 32 * 1000).toISOString(),
    availableQuantity: 8,
    maxPerMember: 2,
    partnerStoreId: 'out_1',
    partnerStoreName: 'L1 Discovery Hub — Cyber City',
  },
];

export const INITIAL_MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'FREE',
    name: 'Guest Discovery',
    priceYr: 0,
    description: 'Standard browsing & store locator access.',
    features: [
      'Browse local partner stores & directions',
      'Search imported & local liquor catalogue',
    ],
    isPopular: false,
  },
  {
    id: 'PREMIUM',
    name: 'Member Pass',
    priceYr: 499,
    description: 'First access to sales, partner discounts & wishlist alerts.',
    features: [
      'Early access to special sales 24 hours before non-members',
      'Member-only prices (Save up to 20%)',
      'Exclusive partner store discounts',
    ],
    isPopular: true,
  },
  {
    id: 'PRO',
    name: 'VIP Reserve Club',
    priceYr: 999,
    description: 'Exclusive lounge tasting passes & concierge support.',
    features: [
      'All Member Pass features included',
      'VIP Tasting Room Pass at partner outlets',
    ],
    isPopular: false,
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'v1',
    legalName: 'Gurgaon Prime Spirits Pvt Ltd',
    tradeName: 'L1 Discovery Hub — Cyber City',
    ownerUid: 'user_vendor_1',
    gstin: '06AAACG1234F1Z5',
    status: 'ACTIVE',
    jurisdictionId: 'HR',
    complianceStatus: 'APPROVED',
    createdAt: '2025-06-15T10:00:00Z',
    updatedAt: '2025-06-15T10:00:00Z',
  },
];

export const INITIAL_LICENCES: Licence[] = [
  {
    id: 'lic_1',
    outletId: 'out_1',
    vendorId: 'v1',
    type: 'L-2',
    number: 'HR-GUR-L2-2025-0042',
    issueDate: '2025-06-12',
    expiryDate: '2027-03-31',
    authority: 'Excise & Taxation Department, Govt of Haryana',
    documentPath: 'licences/v1_l2_cert.pdf',
    documentName: 'Haryana_L2_Licence_CyberHub_2025_27.pdf',
    verificationStatus: 'APPROVED',
    reviewerNotes: 'Verified against official licensee database search.',
    reviewedBy: 'compliance_officer_1',
    reviewedAt: '2025-06-14T11:00:00Z',
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'off_gold',
    outletId: 'out_1',
    vendorId: 'v1',
    title: 'Permitted Discovery Gift: Twin Crystal Champagne Flutes',
    description: 'Receive twin lead-free crystal Champagne flutes with verified discovery of Armand de Brignac Gold.',
    validFrom: '2026-08-01',
    validTo: '2026-10-31',
    status: 'LIVE',
    complianceStatus: 'APPROVED',
    terms: ['Permitted platform discovery gift accessory only.'],
    productCategory: 'Wine',
    createdAt: '2026-08-01T10:00:00Z',
  },
];
